'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Delete
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''TeamValidationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''TeamNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TeamDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TeamNameRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamNameRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''DeleteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''TeamMessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamMessageLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TeamNameSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamNameSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''PlayerValidationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary
    
    '''<summary>
    '''PlayerTeamNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerTeamNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PlayerTeamDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerTeamDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PlayerTeamRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerTeamRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''PlayerNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PlayerNameDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerNameDropDownList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''PlayerRequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerRequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''PlayerDeleteButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerDeleteButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PlayerMessageLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerMessageLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PlayerTeamNameSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerTeamNameSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''PlayerNameSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlayerNameSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource
End Class
